# Generated by Django 2.2.1 on 2019-07-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20190729_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='market/images'),
            preserve_default=False,
        ),
    ]
