# Generated by Django 2.2.1 on 2019-08-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_orderupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
