# Generated by Django 2.2.1 on 2019-08-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_delete_orderupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('order_status', models.CharField(default='order Placed', max_length=500)),
            ],
        ),
    ]
