# Generated by Django 2.2.1 on 2019-08-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
