# Generated by Django 2.2.1 on 2019-07-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='imageContent',
            field=models.ImageField(default='', upload_to='blog/images'),
            preserve_default=False,
        ),
    ]
