# Generated by Django 2.2.1 on 2019-08-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_feed_imagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=50)),
                ('intro', models.TextField()),
                ('heading', models.CharField(max_length=100)),
                ('headingcont', models.TextField(max_length=400)),
                ('subheading', models.CharField(max_length=400)),
                ('subcont', models.TextField(max_length=1500)),
            ],
        ),
    ]
